name: Deploy to Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/masterduel-counter
            git stash
            git pull origin master

            cd /var/www/masterduel-counter/backend
            npm ci --legacy-peer-deps || npm install --legacy-peer-deps
            npx prisma db push
            npx prisma generate
            npm run build
            pm2 restart masterduel-backend || pm2 start npm --name "masterduel-backend" -- start

            cd /var/www/masterduel-counter/frontend
            npm ci || npm install
            npm run build

            pm2 save
